apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
        app: app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: arn:aws:ecr:us-east-1:531185373103:repository/my-first-ecr-repo/service1.app:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always


---

