apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
        app: app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: 720766170633.dkr.ecr.us-east-2.amazonaws.com/service1.app:latest
          image: 720766170633.dkr.ecr.us-east-2.amazonaws.com/service2.app:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always